[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "clocks-and-timers-tasks"
version = "0.1.0"

[dependencies]
aux9_tasks = { path = "auxiliary" }
cortex-m-rt = "0.6.3"
